#!/usr/bin/env bash
# Concatenate the modular source into a single distributable stylesheet:
#   1. the shared corporate system (css/*.css)
#   2. every program skin (programs/<slug>/skin.css)
# Usage: ./build.sh
set -euo pipefail
cd "$(dirname "$0")"

OUT="dist/gsc-design-system.css"
# Shared corporate layer (order matters).
PARTS=(fonts tokens base typography utilities components)

{
  echo "/* GSC Design System — bundled build. Generated by build.sh — do not edit by hand. */"
  echo "/* Global Sports Corporation · Live the dream. */"
  echo ""
  for p in "${PARTS[@]}"; do
    cat "css/${p}.css"
    echo ""
  done
  # Program skins — colocated in programs/<slug>/skin.css (self-contained per academy).
  echo "/* ===== Program skins (programs/<slug>/skin.css) ===== */"
  echo ""
  for skin in programs/*/skin.css; do
    cat "$skin"
    echo ""
  done
} > "$OUT"

echo "Built $OUT ($(wc -l < "$OUT") lines) — core + $(ls programs/*/skin.css | wc -l) program skins"
