#!/usr/bin/env bash
# Concatenate the modular source in css/ into a single distributable stylesheet.
# Usage: ./build.sh
set -euo pipefail
cd "$(dirname "$0")"

OUT="dist/gsc-design-system.css"
PARTS=(fonts tokens base typography utilities components)

{
  echo "/* GSC Design System — bundled build. Generated by build.sh — do not edit by hand. */"
  echo "/* Global Sports Corporation · Live the dream. */"
  echo ""
  for p in "${PARTS[@]}"; do
    cat "css/${p}.css"
    echo ""
  done
} > "$OUT"

echo "Built $OUT ($(wc -l < "$OUT") lines)"
